trigger: none

jobs:
- job: terraform_test
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: pwd
  - bash: ls -aRl
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: azuron-sc-workload-identity
  - script: |
      docker run -w /tmp/codebase -v $(Pipeline.Workspace)/s:/tmp/codebase azuron.azurecr.io/azure-cli-terraform:0.0.1 /tmp/codebase/terraform-init-apply.sh