trigger: none

jobs:
- job: terraform_test
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: pwd
  - bash: ls -aRl
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: azuron-sc-workload-identity
  - script: |
      docker run -v /home/vsts/work/1/s:/tmp/codebase azuron.azurecr.io/bash -c "ls -aRl /tmp/codebase"
