trigger: none

jobs:
- job: RunTest
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: gareth-play-azuron-uk-pay-as-you-go
  - script: |
      docker run docker pull azuron.azurecr.io/hashicorp/terraform:latest