trigger:
- master

jobs:
- job: terraform_test
  workspace:
    clean: all
  pool: azuron-linux-agent-pool
  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: azuron-sc-service-principal
  - script: |
      az login --identity --username b956e4d2-1f4d-45d5-91c2-baa0c9b9e761
  - script: |
      docker run -w /tmp/codebase \
                 --network host \
                 -e SYSTEM_ACCESSTOKEN=$(System.AccessToken) \
                 -v $(Pipeline.Workspace)/s:/tmp/codebase \
                 azuron.azurecr.io/azure-cli-terraform:0.0.2 \
                 /tmp/codebase/terraform-init-apply.sh