# Don't fire pipeline
trigger: none

# Fire pipeline event if PR related
pr:
- master

jobs:
- job: terraform_test
  workspace:
    clean: all
  pool: azuron-devops-agents

  variables:
  - name: msi_client_id
    value: 78020b6e-cbe3-4999-81d2-9fdbecf2a470    # From existing user managed identity

  steps:
  - task: Bash@3
    displayName: Bring Azure user managed identity onto agent
    inputs:
      targetType: 'inline'
      script: |
        az login --identity --username ${{ variables.msi_client_id }}
        az acr login -n azuron.azurecr.io
  - task: Bash@3
    displayName: TF in container with MSI
    inputs:
      targetType: 'inline'
      script: |
        docker run -w /tmp/codebase \
                  -v $(Pipeline.Workspace)/s:/tmp/codebase:rw \
                  -v $HOME/.azure:/root/.azure:rw \
                  azuron.azurecr.io/azure-cli-terraform:0.0.3 \
                  /tmp/codebase/terraform-init-apply-msi.sh
  - task: Bash@3
    displayName: TF in container with SPN
    inputs:
      targetType: 'inline'
      script: |
        docker run -w /tmp/codebase \
                  -v $(Pipeline.Workspace)/s:/tmp/codebase:rw \
                  -v $HOME/.azure:/root/.azure:rw \
                  azuron.azurecr.io/azure-cli-terraform:0.0.3 \
                  /tmp/codebase/terraform-init-apply-spn.sh
  - task: DeleteFiles@1
    displayName: 'clean *'
    inputs:
      SourceFolder: '$(Pipeline.Workspace)'
      Contents: '**/*'
      RemoveDotFiles: true
    condition: always()