trigger:
- master

jobs:
- job: terraform_test
  workspace:
    clean: all
  pool: azuron-devops-agents

  variables:
  - name: msi_client_id
    value: 72384307-c00c-4ebd-9f6e-44147893c91c

  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: azuron-sc-service-principal
  - task: Bash@3
    displayName: Bring Azure identity onto agent
    inputs:
      targetType: 'inline'
      script: |
        az login --identity --username ${{ variables.msi_client_id }}
  - task: Bash@3
    displayName: Run custom container
    inputs:
      targetType: 'inline'
      script: |
        docker run -w /tmp/codebase \
                  -e LONG_COMMIT_SHA=${sourceVersion:0:7} \
                  -v $(Pipeline.Workspace)/s:/tmp/codebase:rw \
                  -v $HOME/.azure:/root/.azure:rw \
                  azuron.azurecr.io/azure-cli-terraform:0.0.2 \
                  /tmp/codebase/terraform-init-apply.sh
  - task: DeleteFiles@1
    displayName: 'clean *'
    inputs:
      SourceFolder: '$(Pipeline.Workspace)'
      Contents: '**/*'
      RemoveDotFiles: true
    condition: always()