trigger:
- master

jobs:
- job: terraform_test
  workspace:
    clean: all
  pool: azuron-devops-agents-pool

  variables:
  - name: msi_client_id
    value: c6e26877-5362-4b06-9d25-4f878d4e5ab5 

  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: azuron-sc-service-principal
  - task: Bash@3
    displayName: Bring Azure identity onto agent
    inputs:
      targetType: 'inline'
      script: |
        az login --identity --username ${{ variables.msi_client_id }}
  - task: Bash@3
    displayName: Run custom container
    inputs:
      targetType: 'inline'
      script: |
        docker run -w /tmp/codebase \
                  -v $(Pipeline.Workspace)/s:/tmp/codebase:rw \
                  -v $HOME/.azure:/root/.azure:rw \
                  azuron.azurecr.io/azure-cli-terraform:0.0.2 \
                  /tmp/codebase/terraform-init-apply.sh