trigger:
- master

jobs:
- job: terraform_test
  workspace:
    clean: all
  pool: azuron-linux-agents
  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: azuron-sc-service-principal
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azuron-uk-pay-as-you-go(60e1436b-d08b-466d-b42a-98011fed3eb2)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az login --identity --username 51fd5a6e-7973-4801-b2f2-b705280e264b'
      useGlobalConfig: true
  - task: Bash@3
    displayName: Run custom container
    inputs:
      targetType: 'inline'
      script: |
        docker run -w /tmp/codebase \
                  --network host \
                  -e SYSTEM_ACCESSTOKEN=$(System.AccessToken) \
                  -v $(Pipeline.Workspace)/s:/tmp/codebase \
                  azuron.azurecr.io/azure-cli-terraform:0.0.2 \
                  /tmp/codebase/terraform-init-apply.sh