trigger:
- master

jobs:
- job: terraform_test
  workspace:
    clean: all
  pool: azuron-linux-agent-pool
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: "curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/' -H Metadata:true"
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'pwd'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'ls -aRl'
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: azuron-sc-service-principal
  - script: |
      docker run -w /tmp/codebase \
                 --network host \
                 -e SYSTEM_ACCESSTOKEN=$(System.AccessToken) \
                 -v $(Pipeline.Workspace)/s:/tmp/codebase \
                 azuron.azurecr.io/azure-cli-terraform:0.0.2 \
                 /tmp/codebase/terraform-init-apply.sh