trigger:
- master

jobs:
- job: terraform_test
  workspace:
    clean: all
  pool: azuron-linux-agents
  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: azuron-sc-service-principal
  - task: Bash@3
    displayName: Run custom container
    inputs:
      targetType: 'inline'
      script: |
        docker run -w /tmp/codebase \
                  -e SYSTEM_ACCESSTOKEN=$(System.AccessToken) \
                  -v $(Pipeline.Workspace)/s:/tmp/codebase \
                  -v /home/grees/.azure:/root/.azure \
                  azuron.azurecr.io/azure-cli-terraform:0.0.2 \
                  /tmp/codebase/terraform-init-apply.sh